Added ConsolidateArtifacts.bat
fl4re/json pull request #1
Opened 2017-06-29 22:17 UTC by AntoineConffx

Added ConsolidateArtifacts.bat that extracts the json.hpp from src folder and moves it to artifacts folder (will be created if doesn't exist)

2017-06-30 20:55 UTC, mbarnes-sb requested changes
please review comments and provide feedback.

2017-06-30 20:55 UTC, mbarnes-sb commented on ConsolidateArtifacts.bat
> +call "%VS140COMNTOOLS%..\..\VC\bin\vcvars32.bat"
This is 32 bit env. Don't you need 64 bit builds?

2017-06-30 20:55 UTC, mbarnes-sb commented on ConsolidateArtifacts.bat
> +if !errorlevel! neq 0 exit /b !errorlevel!
Modern syntax for this statement is `if errorlevel 1 exit /b %errorlevel%`

2017-06-30 21:18 UTC, AntoineConffx commented on ConsolidateArtifacts.bat
> +if !errorlevel! neq 0 exit /b !errorlevel!
I have updated that file with another small bug fix on line 12.

2017-06-30 22:23 UTC, AntoineConffx commented on ConsolidateArtifacts.bat
> +call "%VS140COMNTOOLS%..\..\VC\bin\vcvars32.bat"
I am now using 64-bit visual studio compiler but the blosc project doesn't provide any configuration properties for building in 64-bit, it's only provided for Win32.
Also added clean up of temporary files and folders used for building

2017-07-05 20:34 UTC, mbarnes-sb approved these changes
looks okay

2017-08-15 22:53 UTC, krunal-patel-fl4re commented on ConsolidateArtifacts.bat
> +set "OUT_DIR=./Artifacts"
should be 'artifacts' with small 'a'

2017-08-15 22:54 UTC, merged